name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: Management-System-for-Rental-SEP490/.github/.github/workflows/deploy-python-service.yml@main
    with:
      service_name: ocr-service
      ecr_keep_tagged: 5
